## Numpy
#### NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

### NumPy is used for fast numerical computations using arrays, while Pandas is used for data manipulation and analysis. Pandas is built on top of NumPy and internally uses NumPy arrays for efficient data handling.

In [1]:
! pip install pandas

Requirement already satisfied: pandas in C:\Users\USER\AppData\Roaming\Python\Python312\site-packages (2.2.0)
Requirement already satisfied: numpy<2,>=1.26.0 in d:\code\venv\Lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\USER\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in C:\Users\USER\AppData\Roaming\Python\Python312\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\USER\AppData\Roaming\Python\Python312\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in C:\Users\USER\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [12]:
import pandas as pd

In [8]:
# Series
### A Pandas Series is a one-dimensional array-like object that can hold any data type. it is similar to a column in a table.

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [16]:
## Create a Series from dictionary

data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [22]:
data = [10, 20, 30]
index = ['a','b','c']
pd.Series(data, index = index)

a    10
b    20
c    30
dtype: int64

In [24]:
## Dataframe
## create a Dataframe from a dictionary of list

data={
    'Name':['Dheeraj','John','Jack'],
    'Age':[21,30,45],
    'City':['Bangalore','New York','Florida']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0  Dheeraj   21  Bangalore
1     John   30   New York
2     Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

In [25]:
import numpy as np
np.array(df)

array([['Dheeraj', 21, 'Bangalore'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [34]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Dheeraj', 'Age':21, 'City':'Bangalore'},
    {'Name':'John', 'Age':34, 'City':'Bangalore'},
    {'Name':'Bappy', 'Age':32, 'City':'Bangalore'},
    {'Name':'Jack', 'Age':32, 'City':'Bangalore'}
]

df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0  Dheeraj   21  Bangalore
1     John   34  Bangalore
2    Bappy   32  Bangalore
3     Jack   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [28]:
df = pd.read_csv('sales_data.csv')
print(df.head(5))

   Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum
2           10003  2024-01-03         Clothing         Levi's 501 Jeans
3           10004  2024-01-04            Books        The Da Vinci Code
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set

   Units Sold  Unit Price  Total Revenue         Region Payment Method
0           2      999.99        1999.98  North America    Credit Card
1           1      499.99         499.99         Europe         PayPal
2           3       69.99         209.97           Asia     Debit Card
3           4       15.99          63.96  North America    Credit Card
4           1       89.99          89.99         Europe         PayPal

In [29]:
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [30]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [33]:
### Accessing Data from Dataframe

data

[{'Name': 'Dheeraj', 'Age': 21, 'City': 'Bangalore'},
 {'Name': 'John', 'Age': 34, 'City': 'Bangalore'},
 {'Name': 'Bappy', 'Age': 32, 'City': 'Bangalore'},
 {'Name': 'Jack', 'Age': 32, 'City': 'Bangalore'}]

In [35]:
df

      Name  Age       City
0  Dheeraj   21  Bangalore
1     John   34  Bangalore
2    Bappy   32  Bangalore
3     Jack   32  Bangalore

In [36]:
type(df['Name'])

pandas.core.series.Series

In [37]:
df['Name']

0    Dheeraj
1       John
2      Bappy
3       Jack
Name: Name, dtype: object

In [38]:
df.loc[0]

Name      Dheeraj
Age            21
City    Bangalore
Name: 0, dtype: object

In [39]:
df.iloc[0]

Name      Dheeraj
Age            21
City    Bangalore
Name: 0, dtype: object

In [40]:
df.loc[0][0]

C:\Users\USER\AppData\Local\Temp\ipykernel_25840\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Dheeraj'

In [42]:
df.iloc[0][2]

C:\Users\USER\AppData\Local\Temp\ipykernel_25840\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Bangalore'